"""add message_id for orderFood

Revision ID: 4f61ef449580
Revises: 7b91b225f622
Create Date: 2025-06-11 14:38:10.070691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f61ef449580'
down_revision: Union[str, None] = '7b91b225f622'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_food', sa.Column('message_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_food', 'message_id')
    # ### end Alembic commands ###
