"""changed MenuORM and FoodsORM, because we dont need float figure

Revision ID: 7b91b225f622
Revises: 2f5ab2502a16
Create Date: 2025-06-06 20:57:34.476272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7b91b225f622'
down_revision: Union[str, None] = '2f5ab2502a16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('foods', 'price_per_unit',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('menu', 'price',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('menu', 'price',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('foods', 'price_per_unit',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    # ### end Alembic commands ###
