"""добавлен гарнир

Revision ID: 8ce8bcb8e0df
Revises: 827dd42efa60
Create Date: 2025-06-23 00:19:40.232816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ce8bcb8e0df'
down_revision: Union[str, None] = '827dd42efa60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods', sa.Column('garnish', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foods', 'garnish')
    # ### end Alembic commands ###
